- hosts: module_instances_polkadot_instance
  become: yes
  become_user: root
  vars_files:
    - group_vars/polkadot.yml

  tasks:

    - name: Ensure timedatectl service is running
      service:
        name: systemd-timesyncd
        state: started

    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    
    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    - name: Install Docker and other utils
      apt:
        name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
        state: present
        update_cache: yes

    - name: Install python/pip 
      apt:
        name: ['python-pip','python-dev','build-essential','python3-pip']
        state: present
        update_cache: yes

    - name: Install python libs for docker
      pip:
        name: docker
        state: present

    - name: Pull Polkadot Docker Image
      docker_image:
        name: parity/polkadot:{{ version }}
        source: pull

    - name: Run Polkadot Docker Image
      command: docker run -d -p 9944:9944 -p 9933:9933 -p 9615:9615 --name node-app-container parity/polkadot:{{ version }}
    
    - name: Verify docker container version
      shell: docker exec polkadot-container polkadot --version
      register: shell_result

    - name: Print Version
      debug:
        var: shell_result.stdout_lines
